project:
  type: website
  output-dir: docs

website:
  title: "ALS data coverage in Canadian forests"
  repo-url: https://github.com/ptompalski/CanadaForestLidarCoverage
  repo-actions:
    - source
    - issue
  navbar:
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - text: Coverage maps
        menu:
          - href: maps.qmd
            text: National overview
          - href: maps-west.qmd
            text: Western Canada
          - href: maps-east.qmd
            text: Eastern Canada
          - href: multitemporal.qmd
            text: Multitemporal data
      - text: Resources
        menu:
          - href: data.qmd
            text: Data access
          - href: log.qmd
            text: Update log
          - href: contact.qmd
            text: Contact
    right: 
      - icon: github
        aria-label: Github
        href: https://github.com/ptompalski/CanadaForestLidarCoverage
        
  # page-footer: 
  #   border: true
  #   center: 
  #     - text: 
        

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: source

